#
# Copyright (C) 2020 gSpot (https://github.com/gSpotx2f/luci-app-temp-status)
#
# This is free software, licensed under the MIT License.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Temperature sensors data for the LuCI status page
LUCI_DEPENDS:=+luci
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-temp-status
PKG_VERSION:=0.3.5
PKG_RELEASE:=2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
